package com.weido.create_bb.registry;

import com.zurrtum.create.client.flywheel.lib.model.baked.PartialModel;
import com.weido.create_bb.BlocksBogies;

public class BogiePartials {
    public static final PartialModel
    SMALL_SHARED_WHEELS = block("bogie/small/shared/wheels"),

    LARGE_SHARED_WHEELS_SINGLE              = block("bogie/large/shared/wheels_single"),
    LARGE_SHARED_WHEELS_BLIND_SINGLE        = block("bogie/large/shared/wheels_b_single"),
    LARGE_SHARED_WHEELS_SEMI_BLIND_SINGLE   = block("bogie/large/shared/wheels_s_b_single"),
    LARGE_SHARED_WHEELS                     = block("bogie/large/shared/wheels"),
    LARGE_SHARED_WHEELS_BLIND               = block("bogie/large/shared/wheels_b"),
    LARGE_SHARED_WHEELS_SEMI_BLIND          = block("bogie/large/shared/wheels_s_b"),
    LARGE_SHARED_ECCENTRIC_CRANK            = block("bogie/large/shared/e_crank"),
    LARGE_L_E_LINK                          = block("bogie/large/shared/left_e_link"),
    LARGE_R_E_LINK                          = block("bogie/large/shared/right_e_link"),
    LARGE_L_U_LINK                          = block("bogie/large/shared/left_u_link"),
    LARGE_R_U_LINK                          = block("bogie/large/shared/right_u_link"),
    LARGE_L_C_LEVER                         = block("bogie/large/shared/left_c_lever"),
    LARGE_R_C_LEVER                         = block("bogie/large/shared/right_c_lever"),
    LARGE_L_V_STEM                          = block("bogie/large/shared/left_v_stem"),
    LARGE_R_V_STEM                          = block("bogie/large/shared/right_v_stem"),
    LARGE_L_P_ROD_WALSCHAERTS               = block("bogie/large/shared/left_p_rod_w"),
    LARGE_R_P_ROD_WALSCHAERTS               = block("bogie/large/shared/right_p_rod_w"),
    LARGE_L_P_ROD_GEARLESS                  = block("bogie/large/shared/left_p_rod_g"),
    LARGE_R_P_ROD_GEARLESS                  = block("bogie/large/shared/right_p_rod_g"),

    EXTRA_LARGE_SHARED_WHEELS_SINGLE        = block("bogie/extra_large/shared/wheels_single"),
    EXTRA_LARGE_SHARED_WHEELS_BLIND_SINGLE         = block("bogie/extra_large/shared/wheels_b_single"),
    EXTRA_LARGE_SHARED_WHEELS_SEMI_BLIND_SINGLE    = block("bogie/extra_large/shared/wheels_s_b_single"),
    EXTRA_LARGE_SHARED_WHEELS               = block("bogie/extra_large/shared/wheels"),
    EXTRA_LARGE_SHARED_WHEELS_BLIND         = block("bogie/extra_large/shared/wheels_b"),
    EXTRA_LARGE_SHARED_WHEELS_SEMI_BLIND    = block("bogie/extra_large/shared/wheels_s_b"),
    EXTRA_LARGE_SHARED_ECCENTRIC_CRANK      = block("bogie/extra_large/shared/e_crank"),
    EXTRA_LARGE_L_E_LINK                    = block("bogie/extra_large/shared/left_e_link"),
    EXTRA_LARGE_R_E_LINK                    = block("bogie/extra_large/shared/right_e_link"),
    EXTRA_LARGE_L_U_LINK                    = block("bogie/extra_large/shared/left_u_link"),
    EXTRA_LARGE_R_U_LINK                    = block("bogie/extra_large/shared/right_u_link"),
    EXTRA_LARGE_L_C_LEVER                   = block("bogie/extra_large/shared/left_c_lever"),
    EXTRA_LARGE_R_C_LEVER                   = block("bogie/extra_large/shared/right_c_lever"),
    EXTRA_LARGE_L_V_STEM                    = block("bogie/extra_large/shared/left_v_stem"),
    EXTRA_LARGE_R_V_STEM                    = block("bogie/extra_large/shared/right_v_stem"),
    EXTRA_LARGE_L_P_ROD_WALSCHAERTS         = block("bogie/extra_large/shared/left_p_rod_w"),
    EXTRA_LARGE_R_P_ROD_WALSCHAERTS         = block("bogie/extra_large/shared/right_p_rod_w"),
    EXTRA_LARGE_L_P_ROD_GEARLESS            = block("bogie/extra_large/shared/left_p_rod_g"),
    EXTRA_LARGE_R_P_ROD_GEARLESS            = block("bogie/extra_large/shared/right_p_rod_g"),

    SMALL_TRAILING_2_FRAME                  = block("bogie/small/t2/frame"),
    SMALL_TRAILING_4_FRAME                  = block("bogie/small/t4/frame"),
    SMALL_TRAILING_6_FRAME                  = block("bogie/small/t6/frame"),
    SMALL_TRAILING_8_FRAME                  = block("bogie/small/t8/frame"),

    SMALL_OFFSET_2_FRAME                    = block("bogie/small/s2e/frame"),
    SMALL_BOGIE_2_FRAME                     = block("bogie/small/s2/frame"),
    SMALL_BOGIE_6_FRAME                     = block("bogie/small/s6/frame"),
    SMALL_BOGIE_8_FRAME                     = block("bogie/small/s8/frame"),
    SMALL_BOGIE_10_FRAME                    = block("bogie/small/s10/frame"),

    LARGE_2P_FRAME                          = block("bogie/large/l2p/frame"),
    LARGE_2P_BELTS                          = block("bogie/large/l2p/belts"),

    LARGE_4P_FRAME                          = block("bogie/large/l4p/frame"),
    LARGE_4P_BELTS                          = block("bogie/large/l4p/belts"),
    LARGE_4P_L_C_ROD                        = block("bogie/large/l4p/left_c_rod"),
    LARGE_4P_R_C_ROD                        = block("bogie/large/l4p/right_c_rod"),

    LARGE_6P_FRAME                          = block("bogie/large/l6p/frame"),
    LARGE_6P_BELTS                          = block("bogie/large/l6p/belts"),
    LARGE_6P_L_C_ROD                        = block("bogie/large/l6p/left_c_rod"),
    LARGE_6P_R_C_ROD                        = block("bogie/large/l6p/right_c_rod"),

    LARGE_6EP_FRAME                          = block("bogie/large/l6ep/frame"),
    LARGE_6EP_L_C_ROD                        = block("bogie/large/l6ep/left_c_rod"),
    LARGE_6EP_R_C_ROD                        = block("bogie/large/l6ep/right_c_rod"),

    LARGE_8P_FRAME                          = block("bogie/large/l8p/frame"),
    LARGE_8P_BELTS                          = block("bogie/large/l8p/belts"),
    LARGE_8P_L_C_ROD                        = block("bogie/large/l8p/left_c_rod"),
    LARGE_8P_R_C_ROD                        = block("bogie/large/l8p/right_c_rod"),

    LARGE_10P_FRAME                         = block("bogie/large/l10p/frame"),
    LARGE_10P_BELTS                         = block("bogie/large/l10p/belts"),
    LARGE_10P_L_C_ROD                       = block("bogie/large/l10p/left_c_rod"),
    LARGE_10P_R_C_ROD                       = block("bogie/large/l10p/right_c_rod"),

    EXTRA_LARGE_2P_FRAME                    = block("bogie/extra_large/xl2p/frame"),
    EXTRA_LARGE_2P_BELTS                    = block("bogie/extra_large/xl2p/belts"),

    EXTRA_LARGE_4P_FRAME                    = block("bogie/extra_large/xl4p/frame"),
    EXTRA_LARGE_4P_BELTS                    = block("bogie/extra_large/xl4p/belts"),
    EXTRA_LARGE_4P_L_C_ROD                  = block("bogie/extra_large/xl4p/left_c_rod"),
    EXTRA_LARGE_4P_R_C_ROD                  = block("bogie/extra_large/xl4p/right_c_rod"),

    EXTRA_LARGE_6P_FRAME                    = block("bogie/extra_large/xl6p/frame"),
    EXTRA_LARGE_6P_BELTS                    = block("bogie/extra_large/xl6p/belts"),
    EXTRA_LARGE_6P_L_C_ROD                  = block("bogie/extra_large/xl6p/left_c_rod"),
    EXTRA_LARGE_6P_R_C_ROD                  = block("bogie/extra_large/xl6p/right_c_rod"),

    EXTRA_LARGE_6EP_FRAME                    = block("bogie/extra_large/xl6ep/frame"),
    EXTRA_LARGE_6EP_L_C_ROD                  = block("bogie/extra_large/xl6ep/left_c_rod"),
    EXTRA_LARGE_6EP_R_C_ROD                  = block("bogie/extra_large/xl6ep/right_c_rod"),

    EXTRA_LARGE_8P_FRAME                    = block("bogie/extra_large/xl8p/frame"),
    EXTRA_LARGE_8P_BELTS                    = block("bogie/extra_large/xl8p/belts"),
    EXTRA_LARGE_8P_L_C_ROD                  = block("bogie/extra_large/xl8p/left_c_rod"),
    EXTRA_LARGE_8P_R_C_ROD                  = block("bogie/extra_large/xl8p/right_c_rod"),

    EXTRA_LARGE_10P_FRAME                   = block("bogie/extra_large/xl10p/frame"),
    EXTRA_LARGE_10P_BELTS                   = block("bogie/extra_large/xl10p/belts"),
    EXTRA_LARGE_10P_L_C_ROD                 = block("bogie/extra_large/xl10p/left_c_rod"),
    EXTRA_LARGE_10P_R_C_ROD                 = block("bogie/extra_large/xl10p/right_c_rod"),

    LARGE_12P_FRAME                         = block("bogie/large/l12p/frame"),
    LARGE_12P_L_C_ROD                       = block("bogie/large/l12p/left_c_rod"),
    LARGE_12P_R_C_ROD                       = block("bogie/large/l12p/right_c_rod"),

    LARGE_4C_FRAME                          = block("bogie/large/l4c/frame"),
    LARGE_4C_L_SLIDER                       = block("bogie/large/l4c/l_slider"),
    LARGE_4C_R_SLIDER                       = block("bogie/large/l4c/r_slider"),
    LARGE_4C_L_PIN                          = block("bogie/large/l4c/l_pin"),
    LARGE_4C_R_PIN                          = block("bogie/large/l4c/r_pin"),

    LARGE_6C_FRAME                          = block("bogie/large/l6c/frame"),
    LARGE_6C_L_SLIDER                       = block("bogie/large/l6c/l_slider"),
    LARGE_6C_R_SLIDER                       = block("bogie/large/l6c/r_slider"),
    LARGE_6C_L_PIN                          = block("bogie/large/l6c/l_pin"),
    LARGE_6C_R_PIN                          = block("bogie/large/l6c/r_pin"),

    LARGE_8C_FRAME                          = block("bogie/large/l8c/frame"),
    LARGE_8C_L_SLIDER                       = block("bogie/large/l8c/l_slider"),
    LARGE_8C_R_SLIDER                       = block("bogie/large/l8c/r_slider"),
    LARGE_8C_L_PIN                          = block("bogie/large/l8c/l_pin"),
    LARGE_8C_R_PIN                          = block("bogie/large/l8c/r_pin"),

    LARGE_10C_FRAME                         = block("bogie/large/l10c/frame"),
    LARGE_10C_L_SLIDER                      = block("bogie/large/l10c/l_slider"),
    LARGE_10C_R_SLIDER                      = block("bogie/large/l10c/r_slider"),
    LARGE_10C_L_PIN                         = block("bogie/large/l10c/l_pin"),
    LARGE_10C_R_PIN                         = block("bogie/large/l10c/r_pin"),

    LARGE_12C_FRAME                         = block("bogie/large/l12c/frame"),
    LARGE_12C_L_SLIDER                      = block("bogie/large/l12c/l_slider"),
    LARGE_12C_R_SLIDER                      = block("bogie/large/l12c/r_slider"),
    LARGE_12C_L_PIN                         = block("bogie/large/l12c/l_pin"),
    LARGE_12C_R_PIN                         = block("bogie/large/l12c/r_pin"),

    EXTRA_LARGE_2C_FRAME                    = block("bogie/extra_large/xl2c/frame"),
    EXTRA_LARGE_2C_L_SLIDER                 = block("bogie/extra_large/xl2c/l_slider"),
    EXTRA_LARGE_2C_R_SLIDER                 = block("bogie/extra_large/xl2c/r_slider"),
    EXTRA_LARGE_2C_L_PIN                    = block("bogie/extra_large/xl2c/l_pin"),
    EXTRA_LARGE_2C_R_PIN                    = block("bogie/extra_large/xl2c/r_pin"),

    EXTRA_LARGE_4C_FRAME                    = block("bogie/extra_large/xl4c/frame"),
    EXTRA_LARGE_4C_L_SLIDER                 = block("bogie/extra_large/xl4c/l_slider"),
    EXTRA_LARGE_4C_R_SLIDER                 = block("bogie/extra_large/xl4c/r_slider"),
    EXTRA_LARGE_4C_L_PIN                    = block("bogie/extra_large/xl4c/l_pin"),
    EXTRA_LARGE_4C_R_PIN                    = block("bogie/extra_large/xl4c/r_pin"),

    EXTRA_LARGE_6C_FRAME                    = block("bogie/extra_large/xl6c/frame"),
    EXTRA_LARGE_6C_L_SLIDER                 = block("bogie/extra_large/xl6c/l_slider"),
    EXTRA_LARGE_6C_R_SLIDER                 = block("bogie/extra_large/xl6c/r_slider"),
    EXTRA_LARGE_6C_L_PIN                    = block("bogie/extra_large/xl6c/l_pin"),
    EXTRA_LARGE_6C_R_PIN                    = block("bogie/extra_large/xl6c/r_pin"),

    EXTRA_LARGE_8C_FRAME                    = block("bogie/extra_large/xl8c/frame"),
    EXTRA_LARGE_8C_L_SLIDER                 = block("bogie/extra_large/xl8c/l_slider"),
    EXTRA_LARGE_8C_R_SLIDER                 = block("bogie/extra_large/xl8c/r_slider"),
    EXTRA_LARGE_8C_L_PIN                    = block("bogie/extra_large/xl8c/l_pin"),
    EXTRA_LARGE_8C_R_PIN                    = block("bogie/extra_large/xl8c/r_pin"),

    EXTRA_LARGE_10C_FRAME                   = block("bogie/extra_large/xl10c/frame"),
    EXTRA_LARGE_10C_L_SLIDER                = block("bogie/extra_large/xl10c/l_slider"),
    EXTRA_LARGE_10C_R_SLIDER                = block("bogie/extra_large/xl10c/r_slider"),
    EXTRA_LARGE_10C_L_PIN                   = block("bogie/extra_large/xl10c/l_pin"),
    EXTRA_LARGE_10C_R_PIN                   = block("bogie/extra_large/xl10c/r_pin"),

    LARGE_2L_FRAME                          = block("bogie/large/l2l/frame"),
    LARGE_2L_L_C_ROD                        = block("bogie/large/l2l/left_c_rod"),
    LARGE_2L_R_C_ROD                        = block("bogie/large/l2l/right_c_rod"),

    LARGE_4L_FRAME                          = block("bogie/large/l4l/frame"),
    LARGE_4L_L_C_ROD                        = block("bogie/large/l4l/left_c_rod"),
    LARGE_4L_R_C_ROD                        = block("bogie/large/l4l/right_c_rod"),

    LARGE_4LE_FRAME                          = block("bogie/large/l4le/frame"),
    LARGE_4LE_L_C_ROD                        = block("bogie/large/l4le/left_c_rod"),
    LARGE_4LE_R_C_ROD                        = block("bogie/large/l4le/right_c_rod"),

    LARGE_6L_FRAME                          = block("bogie/large/l6l/frame"),
    LARGE_6L_L_C_ROD                        = block("bogie/large/l6l/left_c_rod"),
    LARGE_6L_R_C_ROD                        = block("bogie/large/l6l/right_c_rod"),

    LARGE_6LE_FRAME                          = block("bogie/large/l6le/frame"),
    LARGE_6LE_L_C_ROD                       = block("bogie/large/l6le/left_c_rod"),
    LARGE_6LE_R_C_ROD                       = block("bogie/large/l6le/right_c_rod"),

    LARGE_8L_FRAME                          = block("bogie/large/l8l/frame"),
    LARGE_8L_L_C_ROD                        = block("bogie/large/l8l/left_c_rod"),
    LARGE_8L_R_C_ROD                        = block("bogie/large/l8l/right_c_rod"),

    LARGE_10L_FRAME                         = block("bogie/large/l10l/frame"),
    LARGE_10L_L_C_ROD                       = block("bogie/large/l10l/left_c_rod"),
    LARGE_10L_R_C_ROD                       = block("bogie/large/l10l/right_c_rod"),

    LARGE_12L_FRAME                         = block("bogie/large/l12l/frame"),
    LARGE_12L_L_C_ROD                       = block("bogie/large/l12l/left_c_rod"),
    LARGE_12L_R_C_ROD                       = block("bogie/large/l12l/right_c_rod"),

    EXTRA_LARGE_2L_FRAME                    = block("bogie/extra_large/xl2l/frame"),

    EXTRA_LARGE_4L_FRAME                    = block("bogie/extra_large/xl4l/frame"),
    EXTRA_LARGE_4L_L_C_ROD                  = block("bogie/extra_large/xl4l/left_c_rod"),
    EXTRA_LARGE_4L_R_C_ROD                  = block("bogie/extra_large/xl4l/right_c_rod"),

    EXTRA_LARGE_4LE_FRAME                    = block("bogie/extra_large/xl4le/frame"),
    EXTRA_LARGE_4LE_L_C_ROD                  = block("bogie/extra_large/xl4le/left_c_rod"),
    EXTRA_LARGE_4LE_R_C_ROD                  = block("bogie/extra_large/xl4le/right_c_rod"),

    EXTRA_LARGE_6L_FRAME                    = block("bogie/extra_large/xl6l/frame"),
    EXTRA_LARGE_6L_L_C_ROD                  = block("bogie/extra_large/xl6l/left_c_rod"),
    EXTRA_LARGE_6L_R_C_ROD                  = block("bogie/extra_large/xl6l/right_c_rod"),

    EXTRA_LARGE_6LE_FRAME                    = block("bogie/extra_large/xl6le/frame"),
    EXTRA_LARGE_6LE_L_C_ROD                 = block("bogie/extra_large/xl6le/left_c_rod"),
    EXTRA_LARGE_6LE_R_C_ROD                 = block("bogie/extra_large/xl6le/right_c_rod"),

    EXTRA_LARGE_8L_FRAME                    = block("bogie/extra_large/xl8l/frame"),
    EXTRA_LARGE_8L_L_C_ROD                  = block("bogie/extra_large/xl8l/left_c_rod"),
    EXTRA_LARGE_8L_R_C_ROD                  = block("bogie/extra_large/xl8l/right_c_rod"),

    EXTRA_LARGE_10L_FRAME                   = block("bogie/extra_large/xl10l/frame"),
    EXTRA_LARGE_10L_L_C_ROD                 = block("bogie/extra_large/xl10l/left_c_rod"),
    EXTRA_LARGE_10L_R_C_ROD                 = block("bogie/extra_large/xl10l/right_c_rod"),

    LARGE_4S_FRAME                          = block("bogie/large/l4s/frame"),
    LARGE_4S_L_C_ROD                        = block("bogie/large/l4s/left_c_rod"),
    LARGE_4S_R_C_ROD                        = block("bogie/large/l4s/right_c_rod"),

    LARGE_6S_FRAME                          = block("bogie/large/l6s/frame"),
    LARGE_6S_L_C_ROD                        = block("bogie/large/l6s/left_c_rod"),
    LARGE_6S_R_C_ROD                        = block("bogie/large/l6s/right_c_rod"),

    LARGE_6SE_FRAME                          = block("bogie/large/l6se/frame"),
    LARGE_6SE_L_C_ROD                       = block("bogie/large/l6se/left_c_rod"),
    LARGE_6SE_R_C_ROD                       = block("bogie/large/l6se/right_c_rod"),

    LARGE_8S_FRAME                          = block("bogie/large/l8s/frame"),
    LARGE_8S_L_C_ROD                        = block("bogie/large/l8s/left_c_rod"),
    LARGE_8S_R_C_ROD                        = block("bogie/large/l8s/right_c_rod"),

    LARGE_10S_FRAME                         = block("bogie/large/l10s/frame"),
    LARGE_10S_L_C_ROD                       = block("bogie/large/l10s/left_c_rod"),
    LARGE_10S_R_C_ROD                       = block("bogie/large/l10s/right_c_rod"),

    LARGE_12S_FRAME                         = block("bogie/large/l12s/frame"),
    LARGE_12S_L_C_ROD                       = block("bogie/large/l12s/left_c_rod"),
    LARGE_12S_R_C_ROD                       = block("bogie/large/l12s/right_c_rod"),

    EXTRA_LARGE_4S_FRAME                    = block("bogie/extra_large/xl4s/frame"),
    EXTRA_LARGE_4S_L_C_ROD                  = block("bogie/extra_large/xl4s/left_c_rod"),
    EXTRA_LARGE_4S_R_C_ROD                  = block("bogie/extra_large/xl4s/right_c_rod"),

    EXTRA_LARGE_6S_FRAME                    = block("bogie/extra_large/xl6s/frame"),
    EXTRA_LARGE_6S_L_C_ROD                  = block("bogie/extra_large/xl6s/left_c_rod"),
    EXTRA_LARGE_6S_R_C_ROD                  = block("bogie/extra_large/xl6s/right_c_rod"),

    EXTRA_LARGE_6SE_FRAME                    = block("bogie/extra_large/xl6se/frame"),
    EXTRA_LARGE_6SE_L_C_ROD                 = block("bogie/extra_large/xl6se/left_c_rod"),
    EXTRA_LARGE_6SE_R_C_ROD                 = block("bogie/extra_large/xl6se/right_c_rod"),

    EXTRA_LARGE_8S_FRAME                    = block("bogie/extra_large/xl8s/frame"),
    EXTRA_LARGE_8S_L_C_ROD                  = block("bogie/extra_large/xl8s/left_c_rod"),
    EXTRA_LARGE_8S_R_C_ROD                  = block("bogie/extra_large/xl8s/right_c_rod"),

    EXTRA_LARGE_10S_FRAME                   = block("bogie/extra_large/xl10s/frame"),
    EXTRA_LARGE_10S_L_C_ROD                 = block("bogie/extra_large/xl10s/left_c_rod"),
    EXTRA_LARGE_10S_R_C_ROD                 = block("bogie/extra_large/xl10s/right_c_rod"),

    LARGE_2LW_FRAME                         = block("bogie/large/l2lw/frame"),
    LARGE_2LW_L_C_ROD                       = block("bogie/large/l2lw/left_c_rod"),
    LARGE_2LW_R_C_ROD                       = block("bogie/large/l2lw/right_c_rod"),

    LARGE_4LW_FRAME                         = block("bogie/large/l4lw/frame"),
    LARGE_4LW_L_C_ROD                       = block("bogie/large/l4lw/left_c_rod"),
    LARGE_4LW_R_C_ROD                       = block("bogie/large/l4lw/right_c_rod"),
    LARGE_4LW_L_M_ROD                       = block("bogie/large/l4lw/left_m_rod"),
    LARGE_4LW_R_M_ROD                       = block("bogie/large/l4lw/right_m_rod"),
    LARGE_4LW_L_R_ROD                       = block("bogie/large/l4lw/left_r_rod"),
    LARGE_4LW_R_R_ROD                       = block("bogie/large/l4lw/right_r_rod"),
    LARGE_4LW_L_E_ROD                       = block("bogie/large/l4lw/left_e_rod"),
    LARGE_4LW_R_E_ROD                       = block("bogie/large/l4lw/right_e_rod"),

    LARGE_4LEW_FRAME                        = block("bogie/large/l4lew/frame"),
    LARGE_4LEW_L_C_ROD                      = block("bogie/large/l4lew/left_c_rod"),
    LARGE_4LEW_R_C_ROD                      = block("bogie/large/l4lew/right_c_rod"),
    LARGE_4LEW_L_M_ROD                      = block("bogie/large/l4lew/left_m_rod"),
    LARGE_4LEW_R_M_ROD                      = block("bogie/large/l4lew/right_m_rod"),
    LARGE_4LEW_L_R_ROD                      = block("bogie/large/l4lew/left_r_rod"),
    LARGE_4LEW_R_R_ROD                      = block("bogie/large/l4lew/right_r_rod"),
    LARGE_4LEW_L_E_ROD                      = block("bogie/large/l4lew/left_e_rod"),
    LARGE_4LEW_R_E_ROD                      = block("bogie/large/l4lew/right_e_rod"),

    LARGE_6LW_FRAME                         = block("bogie/large/l6lw/frame"),
    LARGE_6LW_L_C_ROD                       = block("bogie/large/l6lw/left_c_rod"),
    LARGE_6LW_R_C_ROD                       = block("bogie/large/l6lw/right_c_rod"),
    LARGE_6LW_L_M_ROD                       = block("bogie/large/l6lw/left_m_rod"),
    LARGE_6LW_R_M_ROD                       = block("bogie/large/l6lw/right_m_rod"),
    LARGE_6LW_L_R_ROD                       = block("bogie/large/l6lw/left_r_rod"),
    LARGE_6LW_R_R_ROD                       = block("bogie/large/l6lw/right_r_rod"),
    LARGE_6LW_L_E_ROD                       = block("bogie/large/l6lw/left_e_rod"),
    LARGE_6LW_R_E_ROD                       = block("bogie/large/l6lw/right_e_rod"),

    LARGE_6LEW_FRAME                        = block("bogie/large/l6lew/frame"),
    LARGE_6LEW_L_C_ROD                      = block("bogie/large/l6lew/left_c_rod"),
    LARGE_6LEW_R_C_ROD                      = block("bogie/large/l6lew/right_c_rod"),
    LARGE_6LEW_BELTS                        = block("bogie/large/l6lew/belts"),

    LARGE_8LW_FRAME                         = block("bogie/large/l8lw/frame"),
    LARGE_8LW_L_C_ROD                       = block("bogie/large/l8lw/left_c_rod"),
    LARGE_8LW_R_C_ROD                       = block("bogie/large/l8lw/right_c_rod"),
    LARGE_8LW_L_M_ROD                       = block("bogie/large/l8lw/left_m_rod"),
    LARGE_8LW_R_M_ROD                       = block("bogie/large/l8lw/right_m_rod"),
    LARGE_8LW_L_R_ROD                       = block("bogie/large/l8lw/left_r_rod"),
    LARGE_8LW_R_R_ROD                       = block("bogie/large/l8lw/right_r_rod"),
    LARGE_8LW_L_E_ROD                       = block("bogie/large/l8lw/left_e_rod"),
    LARGE_8LW_R_E_ROD                       = block("bogie/large/l8lw/right_e_rod"),

    LARGE_10LW_FRAME                        = block("bogie/large/l10lw/frame"),
    LARGE_10LW_L_C_ROD                      = block("bogie/large/l10lw/left_c_rod"),
    LARGE_10LW_R_C_ROD                      = block("bogie/large/l10lw/right_c_rod"),
    LARGE_10LW_L_M_ROD                      = block("bogie/large/l10lw/left_m_rod"),
    LARGE_10LW_R_M_ROD                      = block("bogie/large/l10lw/right_m_rod"),
    LARGE_10LW_L_R_ROD                      = block("bogie/large/l10lw/left_r_rod"),
    LARGE_10LW_R_R_ROD                      = block("bogie/large/l10lw/right_r_rod"),
    LARGE_10LW_L_E_ROD                      = block("bogie/large/l10lw/left_e_rod"),
    LARGE_10LW_R_E_ROD                      = block("bogie/large/l10lw/right_e_rod"),

    LARGE_12LW_FRAME                        = block("bogie/large/l12lw/frame"),
    LARGE_12LW_BELTS                        = block("bogie/large/l12lw/belts"),
    LARGE_12LW_L_C_ROD                      = block("bogie/large/l12lw/left_c_rod"),
    LARGE_12LW_R_C_ROD                      = block("bogie/large/l12lw/right_c_rod"),
    LARGE_12LW_L_M_ROD                      = block("bogie/large/l12lw/left_m_rod"),
    LARGE_12LW_R_M_ROD                      = block("bogie/large/l12lw/right_m_rod"),
    LARGE_12LW_L_R_ROD                      = block("bogie/large/l12lw/left_r_rod"),
    LARGE_12LW_R_R_ROD                      = block("bogie/large/l12lw/right_r_rod"),
    LARGE_12LW_L_E_ROD                      = block("bogie/large/l12lw/left_e_rod"),
    LARGE_12LW_R_E_ROD                      = block("bogie/large/l12lw/right_e_rod"),

    EXTRA_LARGE_2LW_FRAME                   = block("bogie/extra_large/xl2lw/frame"),

    EXTRA_LARGE_4LW_FRAME                   = block("bogie/extra_large/xl4lw/frame"),
    EXTRA_LARGE_4LW_L_C_ROD                 = block("bogie/extra_large/xl4lw/left_c_rod"),
    EXTRA_LARGE_4LW_R_C_ROD                 = block("bogie/extra_large/xl4lw/right_c_rod"),
    EXTRA_LARGE_4LW_L_M_ROD                 = block("bogie/extra_large/xl4lw/left_m_rod"),
    EXTRA_LARGE_4LW_R_M_ROD                 = block("bogie/extra_large/xl4lw/right_m_rod"),
    EXTRA_LARGE_4LW_L_R_ROD                 = block("bogie/extra_large/xl4lw/left_r_rod"),
    EXTRA_LARGE_4LW_R_R_ROD                 = block("bogie/extra_large/xl4lw/right_r_rod"),
    EXTRA_LARGE_4LW_L_E_ROD                 = block("bogie/extra_large/xl4lw/left_e_rod"),
    EXTRA_LARGE_4LW_R_E_ROD                 = block("bogie/extra_large/xl4lw/right_e_rod"),

    EXTRA_LARGE_4LEW_FRAME                   = block("bogie/extra_large/xl4lew/frame"),
    EXTRA_LARGE_4LEW_L_C_ROD                 = block("bogie/extra_large/xl4lew/left_c_rod"),
    EXTRA_LARGE_4LEW_R_C_ROD                 = block("bogie/extra_large/xl4lew/right_c_rod"),
    EXTRA_LARGE_4LEW_L_M_ROD                 = block("bogie/extra_large/xl4lew/left_m_rod"),
    EXTRA_LARGE_4LEW_R_M_ROD                 = block("bogie/extra_large/xl4lew/right_m_rod"),
    EXTRA_LARGE_4LEW_L_R_ROD                 = block("bogie/extra_large/xl4lew/left_r_rod"),
    EXTRA_LARGE_4LEW_R_R_ROD                 = block("bogie/extra_large/xl4lew/right_r_rod"),
    EXTRA_LARGE_4LEW_L_E_ROD                 = block("bogie/extra_large/xl4lew/left_e_rod"),
    EXTRA_LARGE_4LEW_R_E_ROD                 = block("bogie/extra_large/xl4lew/right_e_rod"),

    EXTRA_LARGE_6LW_FRAME                   = block("bogie/extra_large/xl6lw/frame"),
    EXTRA_LARGE_6LW_L_C_ROD                 = block("bogie/extra_large/xl6lw/left_c_rod"),
    EXTRA_LARGE_6LW_R_C_ROD                 = block("bogie/extra_large/xl6lw/right_c_rod"),
    EXTRA_LARGE_6LW_L_M_ROD                 = block("bogie/extra_large/xl6lw/left_m_rod"),
    EXTRA_LARGE_6LW_R_M_ROD                 = block("bogie/extra_large/xl6lw/right_m_rod"),
    EXTRA_LARGE_6LW_L_R_ROD                 = block("bogie/extra_large/xl6lw/left_r_rod"),
    EXTRA_LARGE_6LW_R_R_ROD                 = block("bogie/extra_large/xl6lw/right_r_rod"),
    EXTRA_LARGE_6LW_L_E_ROD                 = block("bogie/extra_large/xl6lw/left_e_rod"),
    EXTRA_LARGE_6LW_R_E_ROD                 = block("bogie/extra_large/xl6lw/right_e_rod"),

    EXTRA_LARGE_6LEW_FRAME                  = block("bogie/extra_large/xl6lew/frame"),
    EXTRA_LARGE_6LEW_L_C_ROD                = block("bogie/extra_large/xl6lew/left_c_rod"),
    EXTRA_LARGE_6LEW_R_C_ROD                = block("bogie/extra_large/xl6lew/right_c_rod"),
    EXTRA_LARGE_6LEW_BELTS                  = block("bogie/extra_large/xl6lew/belts"),

    EXTRA_LARGE_8LW_FRAME                   = block("bogie/extra_large/xl8lw/frame"),
    EXTRA_LARGE_8LW_L_C_ROD                 = block("bogie/extra_large/xl8lw/left_c_rod"),
    EXTRA_LARGE_8LW_R_C_ROD                 = block("bogie/extra_large/xl8lw/right_c_rod"),
    EXTRA_LARGE_8LW_L_M_ROD                 = block("bogie/extra_large/xl8lw/left_m_rod"),
    EXTRA_LARGE_8LW_R_M_ROD                 = block("bogie/extra_large/xl8lw/right_m_rod"),
    EXTRA_LARGE_8LW_L_R_ROD                 = block("bogie/extra_large/xl8lw/left_r_rod"),
    EXTRA_LARGE_8LW_R_R_ROD                 = block("bogie/extra_large/xl8lw/right_r_rod"),
    EXTRA_LARGE_8LW_L_E_ROD                 = block("bogie/extra_large/xl8lw/left_e_rod"),
    EXTRA_LARGE_8LW_R_E_ROD                 = block("bogie/extra_large/xl8lw/right_e_rod"),

    EXTRA_LARGE_10LW_FRAME                  = block("bogie/extra_large/xl10lw/frame"),
    EXTRA_LARGE_10LW_L_C_ROD                = block("bogie/extra_large/xl10lw/left_c_rod"),
    EXTRA_LARGE_10LW_R_C_ROD                = block("bogie/extra_large/xl10lw/right_c_rod"),
    EXTRA_LARGE_10LW_L_M_ROD                = block("bogie/extra_large/xl10lw/left_m_rod"),
    EXTRA_LARGE_10LW_R_M_ROD                = block("bogie/extra_large/xl10lw/right_m_rod"),
    EXTRA_LARGE_10LW_L_R_ROD                = block("bogie/extra_large/xl10lw/left_r_rod"),
    EXTRA_LARGE_10LW_R_R_ROD                = block("bogie/extra_large/xl10lw/right_r_rod"),
    EXTRA_LARGE_10LW_L_E_ROD                = block("bogie/extra_large/xl10lw/left_e_rod"),
    EXTRA_LARGE_10LW_R_E_ROD                = block("bogie/extra_large/xl10lw/right_e_rod"),

    LARGE_4SW_FRAME                         = block("bogie/large/l4sw/frame"),
    LARGE_4SW_L_C_ROD                       = block("bogie/large/l4sw/left_c_rod"),
    LARGE_4SW_R_C_ROD                       = block("bogie/large/l4sw/right_c_rod"),
    LARGE_4SW_L_M_ROD                       = block("bogie/large/l4sw/left_m_rod"),
    LARGE_4SW_R_M_ROD                       = block("bogie/large/l4sw/right_m_rod"),
    LARGE_4SW_L_R_ROD                       = block("bogie/large/l4sw/left_r_rod"),
    LARGE_4SW_R_R_ROD                       = block("bogie/large/l4sw/right_r_rod"),
    LARGE_4SW_L_E_ROD                       = block("bogie/large/l4sw/left_e_rod"),
    LARGE_4SW_R_E_ROD                       = block("bogie/large/l4sw/right_e_rod"),

    LARGE_6SW_FRAME                         = block("bogie/large/l6sw/frame"),
    LARGE_6SW_L_C_ROD                       = block("bogie/large/l6sw/left_c_rod"),
    LARGE_6SW_R_C_ROD                       = block("bogie/large/l6sw/right_c_rod"),
    LARGE_6SW_L_M_ROD                       = block("bogie/large/l6sw/left_m_rod"),
    LARGE_6SW_R_M_ROD                       = block("bogie/large/l6sw/right_m_rod"),
    LARGE_6SW_L_R_ROD                       = block("bogie/large/l6sw/left_r_rod"),
    LARGE_6SW_R_R_ROD                       = block("bogie/large/l6sw/right_r_rod"),
    LARGE_6SW_L_E_ROD                       = block("bogie/large/l6sw/left_e_rod"),
    LARGE_6SW_R_E_ROD                       = block("bogie/large/l6sw/right_e_rod"),

    LARGE_6SEW_FRAME                        = block("bogie/large/l6sew/frame"),
    LARGE_6SEW_L_C_ROD                      = block("bogie/large/l6sew/left_c_rod"),
    LARGE_6SEW_R_C_ROD                      = block("bogie/large/l6sew/right_c_rod"),

    LARGE_8SW_FRAME                         = block("bogie/large/l8sw/frame"),
    LARGE_8SW_L_C_ROD                       = block("bogie/large/l8sw/left_c_rod"),
    LARGE_8SW_R_C_ROD                       = block("bogie/large/l8sw/right_c_rod"),
    LARGE_8SW_L_M_ROD                       = block("bogie/large/l8sw/left_m_rod"),
    LARGE_8SW_R_M_ROD                       = block("bogie/large/l8sw/right_m_rod"),
    LARGE_8SW_L_R_ROD                       = block("bogie/large/l8sw/left_r_rod"),
    LARGE_8SW_R_R_ROD                       = block("bogie/large/l8sw/right_r_rod"),
    LARGE_8SW_L_E_ROD                       = block("bogie/large/l8sw/left_e_rod"),
    LARGE_8SW_R_E_ROD                       = block("bogie/large/l8sw/right_e_rod"),

    LARGE_10SW_FRAME                        = block("bogie/large/l10sw/frame"),
    LARGE_10SW_L_C_ROD                      = block("bogie/large/l10sw/left_c_rod"),
    LARGE_10SW_R_C_ROD                      = block("bogie/large/l10sw/right_c_rod"),
    LARGE_10SW_L_M_ROD                      = block("bogie/large/l10sw/left_m_rod"),
    LARGE_10SW_R_M_ROD                      = block("bogie/large/l10sw/right_m_rod"),
    LARGE_10SW_L_R_ROD                      = block("bogie/large/l10sw/left_r_rod"),
    LARGE_10SW_R_R_ROD                      = block("bogie/large/l10sw/right_r_rod"),
    LARGE_10SW_L_E_ROD                      = block("bogie/large/l10sw/left_e_rod"),
    LARGE_10SW_R_E_ROD                      = block("bogie/large/l10sw/right_e_rod"),

    LARGE_12SW_FRAME                        = block("bogie/large/l12sw/frame"),
    LARGE_12SW_L_C_ROD                      = block("bogie/large/l12sw/left_c_rod"),
    LARGE_12SW_R_C_ROD                      = block("bogie/large/l12sw/right_c_rod"),
    LARGE_12SW_L_M_ROD                      = block("bogie/large/l12sw/left_m_rod"),
    LARGE_12SW_R_M_ROD                      = block("bogie/large/l12sw/right_m_rod"),
    LARGE_12SW_L_R_ROD                      = block("bogie/large/l12sw/left_r_rod"),
    LARGE_12SW_R_R_ROD                      = block("bogie/large/l12sw/right_r_rod"),
    LARGE_12SW_L_E_ROD                      = block("bogie/large/l12sw/left_e_rod"),
    LARGE_12SW_R_E_ROD                      = block("bogie/large/l12sw/right_e_rod"),

    EXTRA_LARGE_4SW_FRAME                   = block("bogie/extra_large/xl4sw/frame"),
    EXTRA_LARGE_4SW_L_C_ROD                 = block("bogie/extra_large/xl4sw/left_c_rod"),
    EXTRA_LARGE_4SW_R_C_ROD                 = block("bogie/extra_large/xl4sw/right_c_rod"),
    EXTRA_LARGE_4SW_L_M_ROD                 = block("bogie/extra_large/xl4sw/left_m_rod"),
    EXTRA_LARGE_4SW_R_M_ROD                 = block("bogie/extra_large/xl4sw/right_m_rod"),
    EXTRA_LARGE_4SW_L_R_ROD                 = block("bogie/extra_large/xl4sw/left_r_rod"),
    EXTRA_LARGE_4SW_R_R_ROD                 = block("bogie/extra_large/xl4sw/right_r_rod"),
    EXTRA_LARGE_4SW_L_E_ROD                 = block("bogie/extra_large/xl4sw/left_e_rod"),
    EXTRA_LARGE_4SW_R_E_ROD                 = block("bogie/extra_large/xl4sw/right_e_rod"),

    EXTRA_LARGE_6SW_FRAME                   = block("bogie/extra_large/xl6sw/frame"),
    EXTRA_LARGE_6SW_L_C_ROD                 = block("bogie/extra_large/xl6sw/left_c_rod"),
    EXTRA_LARGE_6SW_R_C_ROD                 = block("bogie/extra_large/xl6sw/right_c_rod"),
    EXTRA_LARGE_6SW_L_M_ROD                 = block("bogie/extra_large/xl6sw/left_m_rod"),
    EXTRA_LARGE_6SW_R_M_ROD                 = block("bogie/extra_large/xl6sw/right_m_rod"),
    EXTRA_LARGE_6SW_L_R_ROD                 = block("bogie/extra_large/xl6sw/left_r_rod"),
    EXTRA_LARGE_6SW_R_R_ROD                 = block("bogie/extra_large/xl6sw/right_r_rod"),
    EXTRA_LARGE_6SW_L_E_ROD                 = block("bogie/extra_large/xl6sw/left_e_rod"),
    EXTRA_LARGE_6SW_R_E_ROD                 = block("bogie/extra_large/xl6sw/right_e_rod"),

    EXTRA_LARGE_6SEW_FRAME                  = block("bogie/extra_large/xl6sew/frame"),
    EXTRA_LARGE_6SEW_L_C_ROD                = block("bogie/extra_large/xl6sew/left_c_rod"),
    EXTRA_LARGE_6SEW_R_C_ROD                = block("bogie/extra_large/xl6sew/right_c_rod"),

    EXTRA_LARGE_8SW_FRAME                   = block("bogie/extra_large/xl8sw/frame"),
    EXTRA_LARGE_8SW_L_C_ROD                 = block("bogie/extra_large/xl8sw/left_c_rod"),
    EXTRA_LARGE_8SW_R_C_ROD                 = block("bogie/extra_large/xl8sw/right_c_rod"),
    EXTRA_LARGE_8SW_L_M_ROD                 = block("bogie/extra_large/xl8sw/left_m_rod"),
    EXTRA_LARGE_8SW_R_M_ROD                 = block("bogie/extra_large/xl8sw/right_m_rod"),
    EXTRA_LARGE_8SW_L_R_ROD                 = block("bogie/extra_large/xl8sw/left_r_rod"),
    EXTRA_LARGE_8SW_R_R_ROD                 = block("bogie/extra_large/xl8sw/right_r_rod"),
    EXTRA_LARGE_8SW_L_E_ROD                 = block("bogie/extra_large/xl8sw/left_e_rod"),
    EXTRA_LARGE_8SW_R_E_ROD                 = block("bogie/extra_large/xl8sw/right_e_rod"),

    EXTRA_LARGE_10SW_FRAME                  = block("bogie/extra_large/xl10sw/frame"),
    EXTRA_LARGE_10SW_L_C_ROD                = block("bogie/extra_large/xl10sw/left_c_rod"),
    EXTRA_LARGE_10SW_R_C_ROD                = block("bogie/extra_large/xl10sw/right_c_rod"),
    EXTRA_LARGE_10SW_L_M_ROD                = block("bogie/extra_large/xl10sw/left_m_rod"),
    EXTRA_LARGE_10SW_R_M_ROD                = block("bogie/extra_large/xl10sw/right_m_rod"),
    EXTRA_LARGE_10SW_L_R_ROD                = block("bogie/extra_large/xl10sw/left_r_rod"),
    EXTRA_LARGE_10SW_R_R_ROD                = block("bogie/extra_large/xl10sw/right_r_rod"),
    EXTRA_LARGE_10SW_L_E_ROD                = block("bogie/extra_large/xl10sw/left_e_rod"),
    EXTRA_LARGE_10SW_R_E_ROD                = block("bogie/extra_large/xl10sw/right_e_rod")
    ;

    private static PartialModel block(String path) {
        return PartialModel.of(BlocksBogies.asResource("block/" + path));
    }
    public static void init() { BlocksBogies.LOGGER.info("Registered partial models for " + BlocksBogies.MOD_NAME); }
}